from .generic import TableData
from .detection import DetectionTableData
from .object import ObjectTableData
from .non_detection import NonDetectionTableData
from .ss import SSTableData
from .data_quality import DataQualityTableData
from .magstats import MagstatsTableData
from .ps1 import PS1TableData
from .gaia import GaiaTableData
from .reference import ReferenceTableData
from .xmatch import XmatchTableData
from .allwise import AllwiseTableData
from .feature import FeatureTableData
from .probability import ProbabilityTableData