version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  initdb:
    build:
      context: .
    entrypoint: ./scripts/entrypoint_initdb.sh
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts

  webserver:
    build:
      context: .
    entrypoint: ./scripts/entrypoint_webserver.sh
    depends_on:
      - initdb
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
      - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
      - AIRFLOW_CONN_AWS_DEFAULT=aws://acess_key_id:secret_access_key@
      - AWS_DEFAULT_REGION=us-east-1
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
    volumes:
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - ./variables:/opt/airflow/variables
    ports:
      - "8080:8080"

  scheduler:
    build:
      context: .
    entrypoint: ./scripts/entrypoint_scheduler.sh
    depends_on:
      - webserver
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
      - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
      - AIRFLOW_CONN_AWS_DEFAULT=aws://acess_key_id:secret_access_key@
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
